default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] if ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: voice_agent_development

test:
  <<: *default
  database: voice_agent_test

production:
  <<: *default
  database: voice_agent_production
